/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bfh_ti_shakytable_I2CTempSensor */

#ifndef _Included_bfh_ti_shakytable_I2CTempSensor
#define _Included_bfh_ti_shakytable_I2CTempSensor
#ifdef __cplusplus
extern "C" {
#endif
#undef bfh_ti_shakytable_I2CTempSensor_MCP9800_CONFIG
#define bfh_ti_shakytable_I2CTempSensor_MCP9800_CONFIG 32L
#undef bfh_ti_shakytable_I2CTempSensor_MCP9800_12_BIT
#define bfh_ti_shakytable_I2CTempSensor_MCP9800_12_BIT 103L
#undef bfh_ti_shakytable_I2CTempSensor_MCP9800_I2C_ADDR
#define bfh_ti_shakytable_I2CTempSensor_MCP9800_I2C_ADDR 28L
#ifdef __cplusplus
}
#endif
#endif
